version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
  disable:
    - gocyclo

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly