// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_logs
WHERE tenant_id = $1
AND ($2::uuid IS NULL OR actor_id = $2)
AND ($3::varchar = '' OR resource_type = $3)
AND ($4::varchar = '' OR action = $4)
AND ($5::varchar = '' OR outcome = $5)
AND ($6::timestamptz IS NULL OR created_at >= $6)
AND ($7::timestamptz IS NULL OR created_at <= $7)
`

type CountAuditLogsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ResourceType string             `json:"resource_type"`
	Action       string             `json:"action"`
	Outcome      string             `json:"outcome"`
	FromDate     pgtype.Timestamptz `json:"from_date"`
	ToDate       pgtype.Timestamptz `json:"to_date"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg *CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAuditLogs,
		arg.TenantID,
		arg.ActorID,
		arg.ResourceType,
		arg.Action,
		arg.Outcome,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const InsertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (tenant_id, actor_id, resource_type, action, outcome, resource_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ResourceType string      `json:"resource_type"`
	Action       string      `json:"action"`
	Outcome      string      `json:"outcome"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg *InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, InsertAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.ResourceType,
		arg.Action,
		arg.Outcome,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const ListAuditLogs = `-- name: ListAuditLogs :many
SELECT
    al.id,
    al.tenant_id,
    al.actor_id,
    u.name AS actor_name,
    u.email AS actor_email,
    al.resource_type,
    al.action,
    al.outcome,
    al.resource_id,
    al.metadata,
    al.ip_address,
    al.user_agent,
    al.created_at
FROM audit_logs al
INNER JOIN users u ON u.id = al.actor_id
WHERE al.tenant_id = $1
AND ($2::uuid IS NULL OR al.actor_id = $2)
AND ($3::varchar = '' OR al.resource_type = $3)
AND ($4::varchar = '' OR al.action = $4)
AND ($5::varchar = '' OR al.outcome = $5)
AND ($6::timestamptz IS NULL OR al.created_at >= $6)
AND ($7::timestamptz IS NULL OR al.created_at <= $7)
ORDER BY al.created_at DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ResourceType string             `json:"resource_type"`
	Action       string             `json:"action"`
	Outcome      string             `json:"outcome"`
	FromDate     pgtype.Timestamptz `json:"from_date"`
	ToDate       pgtype.Timestamptz `json:"to_date"`
	OffsetCount  int32              `json:"offset_count"`
	LimitCount   int32              `json:"limit_count"`
}

type ListAuditLogsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorName    string             `json:"actor_name"`
	ActorEmail   string             `json:"actor_email"`
	ResourceType string             `json:"resource_type"`
	Action       string             `json:"action"`
	Outcome      string             `json:"outcome"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg *ListAuditLogsParams) ([]*ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, ListAuditLogs,
		arg.TenantID,
		arg.ActorID,
		arg.ResourceType,
		arg.Action,
		arg.Outcome,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorEmail,
			&i.ResourceType,
			&i.Action,
			&i.Outcome,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
