// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreatePasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token_hash, expires_at, created_at, used_at
`

type CreatePasswordResetTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg *CreatePasswordResetTokenParams) (*PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, CreatePasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const CreateRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    jti,
    device_info,
    ip_address,
    expires_at
) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, jti, device_info, ip_address, expires_at, created_at, used_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Jti        pgtype.UUID        `json:"jti"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, CreateRefreshToken,
		arg.UserID,
		arg.Jti,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const CreateTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name
) VALUES (
    $1
) RETURNING id, name, enterprise_features, stripe_customer_id, created_at, updated_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, CreateTenant, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnterpriseFeatures,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id,
    email,
    password_hash,
    name,
    status,
    is_internal_user,
    auth_method,
    external_sso_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, email, password_hash, name, is_internal_admin, is_internal_user, created_at, updated_at, deleted_at, status, auth_method, external_sso_id
`

type CreateUserParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
	IsInternalUser bool        `json:"is_internal_user"`
	AuthMethod     string      `json:"auth_method"`
	ExternalSsoID  pgtype.Text `json:"external_sso_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
		arg.IsInternalUser,
		arg.AuthMethod,
		arg.ExternalSsoID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsInternalAdmin,
		&i.IsInternalUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Status,
		&i.AuthMethod,
		&i.ExternalSsoID,
	)
	return &i, err
}

const DeletePasswordResetTokenByUserID = `-- name: DeletePasswordResetTokenByUserID :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokenByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeletePasswordResetTokenByUserID, userID)
	return err
}

const ExistsUserWithEmail = `-- name: ExistsUserWithEmail :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL
)
`

func (q *Queries) ExistsUserWithEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsUserWithEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, used_at FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (*PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, GetPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const GetRefreshTokenByUserID = `-- name: GetRefreshTokenByUserID :one
SELECT id, user_id, jti, device_info, ip_address, expires_at, created_at, used_at, revoked_at FROM refresh_tokens 
WHERE user_id = $1 
AND revoked_at IS NULL 
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, GetRefreshTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const GetTenantAndUserContext = `-- name: GetTenantAndUserContext :one
SELECT 
    tenants.enterprise_features,
    users.is_internal_user
FROM tenants
JOIN users ON users.tenant_id = tenants.id
WHERE tenants.id = $1 AND users.id = $2 AND users.deleted_at IS NULL
`

type GetTenantAndUserContextParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetTenantAndUserContextRow struct {
	EnterpriseFeatures []byte `json:"enterprise_features"`
	IsInternalUser     bool   `json:"is_internal_user"`
}

func (q *Queries) GetTenantAndUserContext(ctx context.Context, arg *GetTenantAndUserContextParams) (*GetTenantAndUserContextRow, error) {
	row := q.db.QueryRow(ctx, GetTenantAndUserContext, arg.TenantID, arg.UserID)
	var i GetTenantAndUserContextRow
	err := row.Scan(&i.EnterpriseFeatures, &i.IsInternalUser)
	return &i, err
}

const GetTenantByID = `-- name: GetTenantByID :one
SELECT id, name, enterprise_features, stripe_customer_id, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error) {
	row := q.db.QueryRow(ctx, GetTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnterpriseFeatures,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, is_internal_admin, is_internal_user, created_at, updated_at, deleted_at, status, auth_method, external_sso_id FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsInternalAdmin,
		&i.IsInternalUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Status,
		&i.AuthMethod,
		&i.ExternalSsoID,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, is_internal_admin, is_internal_user, created_at, updated_at, deleted_at, status, auth_method, external_sso_id FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsInternalAdmin,
		&i.IsInternalUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Status,
		&i.AuthMethod,
		&i.ExternalSsoID,
	)
	return &i, err
}

const MarkPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkPasswordResetTokenAsUsed, id)
	return err
}

const RevokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP 
WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeRefreshToken, jti)
	return err
}

const UpdateRefreshTokenUsed = `-- name: UpdateRefreshTokenUsed :exec
UPDATE refresh_tokens 
SET used_at = CURRENT_TIMESTAMP 
WHERE jti = $1
`

func (q *Queries) UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error {
	_, err := q.db.Exec(ctx, UpdateRefreshTokenUsed, jti)
	return err
}

const UpdateTenantEnterpriseFeatures = `-- name: UpdateTenantEnterpriseFeatures :exec
UPDATE tenants
SET enterprise_features = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateTenantEnterpriseFeaturesParams struct {
	EnterpriseFeatures []byte      `json:"enterprise_features"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenantEnterpriseFeatures(ctx context.Context, arg *UpdateTenantEnterpriseFeaturesParams) error {
	_, err := q.db.Exec(ctx, UpdateTenantEnterpriseFeatures, arg.EnterpriseFeatures, arg.ID)
	return err
}

const UpdateTenantName = `-- name: UpdateTenantName :exec
UPDATE tenants
SET name = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateTenantNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenantName(ctx context.Context, arg *UpdateTenantNameParams) error {
	_, err := q.db.Exec(ctx, UpdateTenantName, arg.Name, arg.ID)
	return err
}
