// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForAddRolesToUser implements pgx.CopyFromSource.
type iteratorForAddRolesToUser struct {
	rows                 []*AddRolesToUserParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddRolesToUser) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddRolesToUser) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].RoleID,
		r.rows[0].TenantID,
	}, nil
}

func (r iteratorForAddRolesToUser) Err() error {
	return nil
}

func (q *Queries) AddRolesToUser(ctx context.Context, arg []*AddRolesToUserParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_roles"}, []string{"user_id", "role_id", "tenant_id"}, &iteratorForAddRolesToUser{rows: arg})
}
