// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"lugia/queries_pregeneration"
)

type InvitationToken struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Jti        pgtype.UUID
	DeviceInfo pgtype.Text
	IpAddress  pgtype.Text
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Plan      string
}

type User struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         queries_pregeneration.UserRole
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Status       string
}
