// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateInvitedUser(ctx context.Context, arg *ActivateInvitedUserParams) error
	CountUsersByTenantID(ctx context.Context, arg *CountUsersByTenantIDParams) (int64, error)
	CreateEmailChangeToken(ctx context.Context, arg *CreateEmailChangeTokenParams) error
	CreateInvitationToken(ctx context.Context, arg *CreateInvitationTokenParams) (*InvitationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg *CreatePasswordResetTokenParams) (*PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error)
	CreateTenant(ctx context.Context, name string) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteEmailChangeTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteInvitationTokensByUserIDAndTenantID(ctx context.Context, arg *DeleteInvitationTokensByUserIDAndTenantIDParams) error
	DeletePasswordResetTokenByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (*EmailChangeToken, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*InvitationToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (*PasswordResetToken, error)
	GetRefreshTokenByJTI(ctx context.Context, jti pgtype.UUID) (*RefreshToken, error)
	GetRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUsersByTenantID(ctx context.Context, arg *GetUsersByTenantIDParams) ([]*GetUsersByTenantIDRow, error)
	InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) (pgtype.UUID, error)
	MarkEmailChangeTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkInvitationTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error
	UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error
	UpdateTenantName(ctx context.Context, arg *UpdateTenantNameParams) error
	UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) error
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
	UserHasPermission(ctx context.Context, arg *UserHasPermissionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
