// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateInvitedUser(ctx context.Context, arg *ActivateInvitedUserParams) error
	AddRolesToUser(ctx context.Context, arg []*AddRolesToUserParams) (int64, error)
	AssignRoleToUser(ctx context.Context, arg *AssignRoleToUserParams) error
	CheckRoleNameExists(ctx context.Context, arg *CheckRoleNameExistsParams) (bool, error)
	CountUsersByTenantID(ctx context.Context, arg *CountUsersByTenantIDParams) (int64, error)
	CreateEmailChangeToken(ctx context.Context, arg *CreateEmailChangeTokenParams) error
	CreateInvitationToken(ctx context.Context, arg *CreateInvitationTokenParams) (*InvitationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg *CreatePasswordResetTokenParams) (*PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error)
	CreateRole(ctx context.Context, arg *CreateRoleParams) (*CreateRoleRow, error)
	CreateRolePermissionsBulk(ctx context.Context, arg *CreateRolePermissionsBulkParams) error
	CreateTenant(ctx context.Context, name string) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteEmailChangeTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteInvitationTokensByUserIDAndTenantID(ctx context.Context, arg *DeleteInvitationTokensByUserIDAndTenantIDParams) error
	DeletePasswordResetTokenByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRolePermissions(ctx context.Context, arg *DeleteRolePermissionsParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	GetAllPermissions(ctx context.Context) ([]*GetAllPermissionsRow, error)
	GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (*EmailChangeToken, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*InvitationToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (*PasswordResetToken, error)
	GetRefreshTokenByJTI(ctx context.Context, jti pgtype.UUID) (*RefreshToken, error)
	GetRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error)
	GetRoleByID(ctx context.Context, arg *GetRoleByIDParams) (*Role, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error)
	GetTenantRolesWithPermissions(ctx context.Context, tenantID pgtype.UUID) ([]*GetTenantRolesWithPermissionsRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserPermissions(ctx context.Context, arg *GetUserPermissionsParams) ([]*GetUserPermissionsRow, error)
	GetUserRoleIDs(ctx context.Context, arg *GetUserRoleIDsParams) ([]pgtype.UUID, error)
	GetUserRolesWithDetails(ctx context.Context, arg *GetUserRolesWithDetailsParams) ([]*GetUserRolesWithDetailsRow, error)
	GetUsersWithRoles(ctx context.Context, arg *GetUsersWithRolesParams) ([]*GetUsersWithRolesRow, error)
	InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) (pgtype.UUID, error)
	MarkEmailChangeTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkInvitationTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	RemoveRolesFromUser(ctx context.Context, arg *RemoveRolesFromUserParams) error
	RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error
	UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error
	UpdateRole(ctx context.Context, arg *UpdateRoleParams) error
	UpdateTenantName(ctx context.Context, arg *UpdateTenantNameParams) error
	UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) error
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
	UserHasPermission(ctx context.Context, arg *UserHasPermissionParams) (bool, error)
	ValidateRolesBelongToTenant(ctx context.Context, arg *ValidateRolesBelongToTenantParams) ([]pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
