// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateInvitedUser(ctx context.Context, arg *ActivateInvitedUserParams) error
	AddIPToWhitelist(ctx context.Context, arg *AddIPToWhitelistParams) (*TenantIpWhitelist, error)
	AddRolesToUser(ctx context.Context, arg []*AddRolesToUserParams) (int64, error)
	AssignRoleToUser(ctx context.Context, arg *AssignRoleToUserParams) error
	CheckIPExists(ctx context.Context, arg *CheckIPExistsParams) (bool, error)
	CheckRoleInUse(ctx context.Context, arg *CheckRoleInUseParams) (bool, error)
	CheckRoleNameExists(ctx context.Context, arg *CheckRoleNameExistsParams) (bool, error)
	ClearTenantIPWhitelist(ctx context.Context, tenantID pgtype.UUID) error
	CountTenantIPWhitelistRules(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountUsersByTenantID(ctx context.Context, arg *CountUsersByTenantIDParams) (int64, error)
	CreateEmailChangeToken(ctx context.Context, arg *CreateEmailChangeTokenParams) error
	// IP Whitelist Revert Token Operations
	CreateIPWhitelistRevertToken(ctx context.Context, arg *CreateIPWhitelistRevertTokenParams) (*IpWhitelistRevertToken, error)
	CreateInvitationToken(ctx context.Context, arg *CreateInvitationTokenParams) (*InvitationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg *CreatePasswordResetTokenParams) (*PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error)
	CreateRole(ctx context.Context, arg *CreateRoleParams) (*CreateRoleRow, error)
	CreateRolePermissionsBulk(ctx context.Context, arg *CreateRolePermissionsBulkParams) error
	CreateTenant(ctx context.Context, name string) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteEmailChangeTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteInvitationTokensByUserIDAndTenantID(ctx context.Context, arg *DeleteInvitationTokensByUserIDAndTenantIDParams) error
	DeletePasswordResetTokenByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteRole(ctx context.Context, arg *DeleteRoleParams) error
	DeleteRolePermissions(ctx context.Context, arg *DeleteRolePermissionsParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	GetAllPermissions(ctx context.Context) ([]*GetAllPermissionsRow, error)
	GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (*EmailChangeToken, error)
	GetIPWhitelistForMiddleware(ctx context.Context, id pgtype.UUID) ([]*GetIPWhitelistForMiddlewareRow, error)
	GetIPWhitelistRevertTokenByHash(ctx context.Context, tokenHash string) (*IpWhitelistRevertToken, error)
	GetIPWhitelistRuleByID(ctx context.Context, arg *GetIPWhitelistRuleByIDParams) (*TenantIpWhitelist, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*InvitationToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (*PasswordResetToken, error)
	GetRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error)
	GetRoleByID(ctx context.Context, arg *GetRoleByIDParams) (*Role, error)
	GetTenantAndUserContext(ctx context.Context, arg *GetTenantAndUserContextParams) (*GetTenantAndUserContextRow, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error)
	GetTenantIPWhitelist(ctx context.Context, tenantID pgtype.UUID) ([]*TenantIpWhitelist, error)
	GetTenantIPWhitelistCIDRs(ctx context.Context, tenantID pgtype.UUID) ([]string, error)
	// Helper query to get current IP whitelist configuration for snapshots
	GetTenantIPWhitelistSnapshot(ctx context.Context, tenantID pgtype.UUID) ([]*GetTenantIPWhitelistSnapshotRow, error)
	GetTenantRolesWithPermissions(ctx context.Context, tenantID pgtype.UUID) ([]*GetTenantRolesWithPermissionsRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserPermissionsWithFallback(ctx context.Context, arg *GetUserPermissionsWithFallbackParams) ([]*GetUserPermissionsWithFallbackRow, error)
	GetUserRoleIDs(ctx context.Context, arg *GetUserRoleIDsParams) ([]pgtype.UUID, error)
	GetUserRolesWithDetails(ctx context.Context, arg *GetUserRolesWithDetailsParams) ([]*GetUserRolesWithDetailsRow, error)
	GetUsersByIPWhitelistEditPermission(ctx context.Context, arg *GetUsersByIPWhitelistEditPermissionParams) ([]*GetUsersByIPWhitelistEditPermissionRow, error)
	GetUsersWithRolesRespectingRBAC(ctx context.Context, arg *GetUsersWithRolesRespectingRBACParams) ([]*GetUsersWithRolesRespectingRBACRow, error)
	InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) (pgtype.UUID, error)
	MarkEmailChangeTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkIPWhitelistRevertTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkInvitationTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, id pgtype.UUID) error
	RemoveIPFromWhitelist(ctx context.Context, arg *RemoveIPFromWhitelistParams) error
	RemoveRolesFromUser(ctx context.Context, arg *RemoveRolesFromUserParams) error
	RestoreIPWhitelistFromSnapshot(ctx context.Context, arg []*RestoreIPWhitelistFromSnapshotParams) (int64, error)
	RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error
	UpdateIPWhitelistLabel(ctx context.Context, arg *UpdateIPWhitelistLabelParams) error
	UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error
	UpdateRole(ctx context.Context, arg *UpdateRoleParams) error
	UpdateTenantName(ctx context.Context, arg *UpdateTenantNameParams) error
	UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) error
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
	UserHasPermission(ctx context.Context, arg *UserHasPermissionParams) (bool, error)
	ValidateRolesBelongToTenant(ctx context.Context, arg *ValidateRolesBelongToTenantParams) ([]pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
