// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ActivateInvitedUser = `-- name: ActivateInvitedUser :exec
UPDATE users
SET password_hash = $1, status = 'active', updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND status = 'pending_verification'
`

type ActivateInvitedUserParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) ActivateInvitedUser(ctx context.Context, arg *ActivateInvitedUserParams) error {
	_, err := q.db.Exec(ctx, ActivateInvitedUser, arg.PasswordHash, arg.ID)
	return err
}

type AddRolesToUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

const AssignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id, tenant_id)
VALUES ($1, $2, $3)
`

type AssignRoleToUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg *AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, AssignRoleToUser, arg.UserID, arg.RoleID, arg.TenantID)
	return err
}

const CountUsersByTenantID = `-- name: CountUsersByTenantID :one
SELECT COUNT(*)
FROM users
WHERE tenant_id = $1 
AND is_internal_user = false
AND deleted_at IS NULL
AND (
    $2 = '' OR 
    name ILIKE '%' || $2 || '%' OR 
    email ILIKE '%' || $2 || '%'
)
`

type CountUsersByTenantIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
}

func (q *Queries) CountUsersByTenantID(ctx context.Context, arg *CountUsersByTenantIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountUsersByTenantID, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateEmailChangeToken = `-- name: CreateEmailChangeToken :exec
INSERT INTO email_change_tokens (
    user_id,
    new_email,
    token_hash,
    expires_at
) VALUES ($1, $2, $3, $4)
`

type CreateEmailChangeTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	NewEmail  string             `json:"new_email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeToken(ctx context.Context, arg *CreateEmailChangeTokenParams) error {
	_, err := q.db.Exec(ctx, CreateEmailChangeToken,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const CreateInvitationToken = `-- name: CreateInvitationToken :one
INSERT INTO invitation_tokens (token_hash, tenant_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, token_hash, expires_at, created_at, used_at
`

type CreateInvitationTokenParams struct {
	TokenHash string             `json:"token_hash"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitationToken(ctx context.Context, arg *CreateInvitationTokenParams) (*InvitationToken, error) {
	row := q.db.QueryRow(ctx, CreateInvitationToken,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const DeleteEmailChangeTokensByUserID = `-- name: DeleteEmailChangeTokensByUserID :exec
DELETE FROM email_change_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailChangeTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteEmailChangeTokensByUserID, userID)
	return err
}

const DeleteInvitationTokensByUserIDAndTenantID = `-- name: DeleteInvitationTokensByUserIDAndTenantID :exec
DELETE FROM invitation_tokens
WHERE user_id = $1 AND tenant_id = $2
`

type DeleteInvitationTokensByUserIDAndTenantIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteInvitationTokensByUserIDAndTenantID(ctx context.Context, arg *DeleteInvitationTokensByUserIDAndTenantIDParams) error {
	_, err := q.db.Exec(ctx, DeleteInvitationTokensByUserIDAndTenantID, arg.UserID, arg.TenantID)
	return err
}

const DeleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteRefreshTokensByUserID, userID)
	return err
}

const GetEmailChangeTokenByHash = `-- name: GetEmailChangeTokenByHash :one
SELECT id, user_id, new_email, token_hash, expires_at, created_at, used_at FROM email_change_tokens
WHERE token_hash = $1 AND used_at IS NULL
`

func (q *Queries) GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (*EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, GetEmailChangeTokenByHash, tokenHash)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const GetInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, created_at, used_at FROM invitation_tokens
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP AND used_at IS NULL
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*InvitationToken, error) {
	row := q.db.QueryRow(ctx, GetInvitationByTokenHash, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const GetUserPermissionsWithFallback = `-- name: GetUserPermissionsWithFallback :many
WITH user_permissions AS (
  -- Get permissions from user's assigned roles (filtered by RBAC status)
  SELECT DISTINCT permissions.resource, permissions.action, 1 as priority
  FROM user_roles
  JOIN roles ON user_roles.role_id = roles.id
  JOIN role_permissions ON user_roles.role_id = role_permissions.role_id
  JOIN permissions ON role_permissions.permission_id = permissions.id
  WHERE user_roles.user_id = $1 
    AND user_roles.tenant_id = $2
    AND (
      $3 = true OR  -- RBAC enabled: use all roles
      roles.is_default = true  -- RBAC disabled: only default roles
    )
),
fallback_permissions AS (
  -- Fallback: Get 閲覧者 permissions if user has no valid roles
  SELECT DISTINCT permissions.resource, permissions.action, 2 as priority
  FROM roles
  JOIN role_permissions ON roles.id = role_permissions.role_id
  JOIN permissions ON role_permissions.permission_id = permissions.id
  WHERE roles.tenant_id = $2
    AND roles.name = '閲覧者'
    AND roles.is_default = true
    AND NOT EXISTS (SELECT 1 FROM user_permissions)
)
SELECT resource, action
FROM (
  SELECT resource, action, priority FROM user_permissions
  UNION ALL
  SELECT resource, action, priority FROM fallback_permissions
) combined
ORDER BY priority, resource, action
`

type GetUserPermissionsWithFallbackParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	RbacEnabled interface{} `json:"rbac_enabled"`
}

type GetUserPermissionsWithFallbackRow struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) GetUserPermissionsWithFallback(ctx context.Context, arg *GetUserPermissionsWithFallbackParams) ([]*GetUserPermissionsWithFallbackRow, error) {
	rows, err := q.db.Query(ctx, GetUserPermissionsWithFallback, arg.UserID, arg.TenantID, arg.RbacEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserPermissionsWithFallbackRow{}
	for rows.Next() {
		var i GetUserPermissionsWithFallbackRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRoleIDs = `-- name: GetUserRoleIDs :many
SELECT role_id FROM user_roles
WHERE user_id = $1 AND tenant_id = $2
`

type GetUserRoleIDsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserRoleIDs(ctx context.Context, arg *GetUserRoleIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, GetUserRoleIDs, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRolesWithDetails = `-- name: GetUserRolesWithDetails :many
SELECT roles.id, roles.name, roles.description
FROM user_roles
JOIN roles ON user_roles.role_id = roles.id
WHERE user_roles.user_id = $1 AND user_roles.tenant_id = $2
`

type GetUserRolesWithDetailsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetUserRolesWithDetailsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetUserRolesWithDetails(ctx context.Context, arg *GetUserRolesWithDetailsParams) ([]*GetUserRolesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, GetUserRolesWithDetails, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserRolesWithDetailsRow{}
	for rows.Next() {
		var i GetUserRolesWithDetailsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersWithRolesRespectingRBAC = `-- name: GetUsersWithRolesRespectingRBAC :many
WITH paginated_users AS (
    SELECT users.id
    FROM users
    WHERE users.tenant_id = $1
    AND users.is_internal_user = false
    AND users.deleted_at IS NULL
    AND (
        $2 = '' OR 
        users.name ILIKE '%' || $2 || '%' OR 
        users.email ILIKE '%' || $2 || '%'
    )
    ORDER BY users.created_at DESC
    LIMIT $4 OFFSET $3
),
user_roles_with_rbac AS (
    SELECT DISTINCT 
        users.id as user_id,
        roles.id as role_id, 
        roles.name as role_name, 
        roles.description as role_description,
        1 as priority
    FROM users
    JOIN paginated_users pu ON users.id = pu.id
    JOIN user_roles ON users.id = user_roles.user_id AND users.tenant_id = user_roles.tenant_id
    JOIN roles ON user_roles.role_id = roles.id
    WHERE (
        $5 = true OR  -- RBAC enabled: use all roles
        roles.is_default = true  -- RBAC disabled: only default roles
    )
),
fallback_roles AS (
    SELECT DISTINCT 
        users.id as user_id,
        roles.id as role_id, 
        roles.name as role_name, 
        roles.description as role_description,
        2 as priority
    FROM users
    JOIN paginated_users pu ON users.id = pu.id
    JOIN roles ON roles.tenant_id = $1
    WHERE roles.name = '閲覧者'
    AND roles.is_default = true
    AND NOT EXISTS (
        SELECT 1 FROM user_roles_with_rbac urwr 
        WHERE urwr.user_id = users.id
    )
)
SELECT 
    users.id, users.email, users.name, users.status, users.created_at, users.updated_at,
    combined_roles.role_id, combined_roles.role_name, combined_roles.role_description
FROM users
JOIN paginated_users pu ON users.id = pu.id
LEFT JOIN (
    SELECT user_id, role_id, role_name, role_description, priority 
    FROM user_roles_with_rbac
    UNION ALL
    SELECT user_id, role_id, role_name, role_description, priority 
    FROM fallback_roles
) combined_roles ON users.id = combined_roles.user_id
ORDER BY users.created_at DESC, users.id, combined_roles.priority, combined_roles.role_name
`

type GetUsersWithRolesRespectingRBACParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	SearchTerm  interface{} `json:"search_term"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
	RbacEnabled interface{} `json:"rbac_enabled"`
}

type GetUsersWithRolesRespectingRBACRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RoleID          pgtype.UUID        `json:"role_id"`
	RoleName        string             `json:"role_name"`
	RoleDescription pgtype.Text        `json:"role_description"`
}

func (q *Queries) GetUsersWithRolesRespectingRBAC(ctx context.Context, arg *GetUsersWithRolesRespectingRBACParams) ([]*GetUsersWithRolesRespectingRBACRow, error) {
	rows, err := q.db.Query(ctx, GetUsersWithRolesRespectingRBAC,
		arg.TenantID,
		arg.SearchTerm,
		arg.OffsetCount,
		arg.LimitCount,
		arg.RbacEnabled,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersWithRolesRespectingRBACRow{}
	for rows.Next() {
		var i GetUsersWithRolesRespectingRBACRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InviteUserToTenant = `-- name: InviteUserToTenant :one
INSERT INTO users (tenant_id, email, password_hash, name, status, auth_method, external_sso_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InviteUserToTenantParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	Name          string      `json:"name"`
	Status        string      `json:"status"`
	AuthMethod    string      `json:"auth_method"`
	ExternalSsoID pgtype.Text `json:"external_sso_id"`
}

func (q *Queries) InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, InviteUserToTenant,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
		arg.AuthMethod,
		arg.ExternalSsoID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const MarkEmailChangeTokenAsUsed = `-- name: MarkEmailChangeTokenAsUsed :exec
UPDATE email_change_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEmailChangeTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkEmailChangeTokenAsUsed, id)
	return err
}

const MarkInvitationTokenAsUsed = `-- name: MarkInvitationTokenAsUsed :exec
UPDATE invitation_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkInvitationTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkInvitationTokenAsUsed, id)
	return err
}

const MarkUserDeletedAndAnonymize = `-- name: MarkUserDeletedAndAnonymize :exec
UPDATE users 
SET 
    email = id::text || '@deleted.invalid',
    name = '削除済みユーザー',
    password_hash = '$2a$10$invalidhashthatshouldnevermatchanythingever',
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkUserDeletedAndAnonymize(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkUserDeletedAndAnonymize, id)
	return err
}

const RemoveRolesFromUser = `-- name: RemoveRolesFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND tenant_id = $2 AND role_id = ANY($3::uuid[])
`

type RemoveRolesFromUserParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Column3  []pgtype.UUID `json:"column_3"`
}

func (q *Queries) RemoveRolesFromUser(ctx context.Context, arg *RemoveRolesFromUserParams) error {
	_, err := q.db.Exec(ctx, RemoveRolesFromUser, arg.UserID, arg.TenantID, arg.Column3)
	return err
}

const UpdateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string      `json:"email"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, UpdateUserEmail, arg.Email, arg.ID)
	return err
}

const UpdateUserExternalSSOID = `-- name: UpdateUserExternalSSOID :exec
UPDATE users
SET external_sso_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserExternalSSOIDParams struct {
	ExternalSsoID pgtype.Text `json:"external_sso_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserExternalSSOID(ctx context.Context, arg *UpdateUserExternalSSOIDParams) error {
	_, err := q.db.Exec(ctx, UpdateUserExternalSSOID, arg.ExternalSsoID, arg.ID)
	return err
}

const UpdateUserName = `-- name: UpdateUserName :exec
UPDATE users
SET name = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, UpdateUserName, arg.Name, arg.ID)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const UpdateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg *UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateUserStatus, arg.Status, arg.ID)
	return err
}

const UserHasPermission = `-- name: UserHasPermission :one
WITH user_permissions AS (
  -- Get permissions from user's assigned roles (filtered by RBAC status)
  SELECT 1 as found
  FROM user_roles
  JOIN roles ON user_roles.role_id = roles.id
  JOIN role_permissions ON user_roles.role_id = role_permissions.role_id
  JOIN permissions ON role_permissions.permission_id = permissions.id
  WHERE user_roles.user_id = $1 
    AND user_roles.tenant_id = $2
    AND permissions.resource = $3
    AND (
        permissions.action = $4 OR 
        ($4 = 'view' AND permissions.action = 'edit')
    )
    AND (
      $5 = true OR  -- RBAC enabled: use all roles
      roles.is_default = true  -- RBAC disabled: only default roles
    )
  LIMIT 1
),
fallback_permissions AS (
  -- Fallback: Check 閲覧者 permissions if user has no valid roles
  SELECT 1 as found
  FROM roles
  JOIN role_permissions ON roles.id = role_permissions.role_id
  JOIN permissions ON role_permissions.permission_id = permissions.id
  WHERE roles.tenant_id = $2
    AND roles.name = '閲覧者'
    AND roles.is_default = true
    AND permissions.resource = $3
    AND (
        permissions.action = $4 OR 
        ($4 = 'view' AND permissions.action = 'edit')
    )
    AND NOT EXISTS (SELECT 1 FROM user_permissions)
  LIMIT 1
)
SELECT EXISTS(
    SELECT 1 FROM user_permissions
    UNION ALL
    SELECT 1 FROM fallback_permissions
)
`

type UserHasPermissionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Resource    string      `json:"resource"`
	Action      string      `json:"action"`
	RbacEnabled interface{} `json:"rbac_enabled"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg *UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, UserHasPermission,
		arg.UserID,
		arg.TenantID,
		arg.Resource,
		arg.Action,
		arg.RbacEnabled,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
