// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ActivateInvitedUser = `-- name: ActivateInvitedUser :exec
UPDATE users
SET password_hash = $1, status = 'active', updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND status = 'pending_verification'
`

type ActivateInvitedUserParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) ActivateInvitedUser(ctx context.Context, arg *ActivateInvitedUserParams) error {
	_, err := q.db.Exec(ctx, ActivateInvitedUser, arg.PasswordHash, arg.ID)
	return err
}

const CountUsersByTenantID = `-- name: CountUsersByTenantID :one
SELECT COUNT(*)
FROM users
WHERE tenant_id = $1 
AND (
    $2 = '' OR 
    name ILIKE '%' || $2 || '%' OR 
    email ILIKE '%' || $2 || '%'
)
`

type CountUsersByTenantIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
}

func (q *Queries) CountUsersByTenantID(ctx context.Context, arg *CountUsersByTenantIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountUsersByTenantID, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateEmailChangeToken = `-- name: CreateEmailChangeToken :exec
INSERT INTO email_change_tokens (
    user_id,
    new_email,
    token_hash,
    expires_at
) VALUES ($1, $2, $3, $4)
`

type CreateEmailChangeTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	NewEmail  string             `json:"new_email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeToken(ctx context.Context, arg *CreateEmailChangeTokenParams) error {
	_, err := q.db.Exec(ctx, CreateEmailChangeToken,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const CreateInvitationToken = `-- name: CreateInvitationToken :one
INSERT INTO invitation_tokens (token_hash, tenant_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, token_hash, expires_at, created_at, used_at
`

type CreateInvitationTokenParams struct {
	TokenHash string             `json:"token_hash"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitationToken(ctx context.Context, arg *CreateInvitationTokenParams) (*InvitationToken, error) {
	row := q.db.QueryRow(ctx, CreateInvitationToken,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const DeleteEmailChangeTokensByUserID = `-- name: DeleteEmailChangeTokensByUserID :exec
DELETE FROM email_change_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailChangeTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteEmailChangeTokensByUserID, userID)
	return err
}

const DeleteInvitationTokensByUserIDAndTenantID = `-- name: DeleteInvitationTokensByUserIDAndTenantID :exec
DELETE FROM invitation_tokens
WHERE user_id = $1 AND tenant_id = $2
`

type DeleteInvitationTokensByUserIDAndTenantIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteInvitationTokensByUserIDAndTenantID(ctx context.Context, arg *DeleteInvitationTokensByUserIDAndTenantIDParams) error {
	_, err := q.db.Exec(ctx, DeleteInvitationTokensByUserIDAndTenantID, arg.UserID, arg.TenantID)
	return err
}

const DeleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteRefreshTokensByUserID, userID)
	return err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const GetEmailChangeTokenByHash = `-- name: GetEmailChangeTokenByHash :one
SELECT id, user_id, new_email, token_hash, expires_at, created_at, used_at FROM email_change_tokens
WHERE token_hash = $1 AND used_at IS NULL
`

func (q *Queries) GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (*EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, GetEmailChangeTokenByHash, tokenHash)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const GetInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, created_at, used_at FROM invitation_tokens
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP AND used_at IS NULL
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (*InvitationToken, error) {
	row := q.db.QueryRow(ctx, GetInvitationByTokenHash, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const GetUsersByTenantID = `-- name: GetUsersByTenantID :many
SELECT id, email, name, status, created_at, updated_at
FROM users
WHERE tenant_id = $1 
AND (
    $2 = '' OR 
    name ILIKE '%' || $2 || '%' OR 
    email ILIKE '%' || $2 || '%'
)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetUsersByTenantIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetUsersByTenantIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUsersByTenantID(ctx context.Context, arg *GetUsersByTenantIDParams) ([]*GetUsersByTenantIDRow, error) {
	rows, err := q.db.Query(ctx, GetUsersByTenantID,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersByTenantIDRow{}
	for rows.Next() {
		var i GetUsersByTenantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InviteUserToTenant = `-- name: InviteUserToTenant :one
INSERT INTO users (tenant_id, email, password_hash, name, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InviteUserToTenantParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Status       string      `json:"status"`
}

func (q *Queries) InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, InviteUserToTenant,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const MarkEmailChangeTokenAsUsed = `-- name: MarkEmailChangeTokenAsUsed :exec
UPDATE email_change_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEmailChangeTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkEmailChangeTokenAsUsed, id)
	return err
}

const MarkInvitationTokenAsUsed = `-- name: MarkInvitationTokenAsUsed :exec
UPDATE invitation_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkInvitationTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, MarkInvitationTokenAsUsed, id)
	return err
}

const UpdateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string      `json:"email"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg *UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, UpdateUserEmail, arg.Email, arg.ID)
	return err
}

const UpdateUserName = `-- name: UpdateUserName :exec
UPDATE users
SET name = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, UpdateUserName, arg.Name, arg.ID)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const UserHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS(
    SELECT 1 FROM user_roles ur
    JOIN roles r ON ur.role_id = r.id
    JOIN role_permissions rp ON r.id = rp.role_id
    JOIN permissions p ON rp.permission_id = p.id
    WHERE ur.user_id = $1 AND r.tenant_id = $2 
    AND p.resource = $3 AND p.action = $4
)
`

type UserHasPermissionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg *UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, UserHasPermission,
		arg.UserID,
		arg.TenantID,
		arg.Resource,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
