linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
  disable:
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

run:
  deadline: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 
  exclude-dirs:
    - vendor