FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

# Use E2E specific configurations by copying them to default config file names
COPY test/svelte.e2e.config.js ./svelte.config.js
COPY test/vite.e2e.config.ts ./vite.config.ts

COPY tsconfig.json ./

RUN npm install --no-frozen-lockfile

COPY . .

RUN npm run build

EXPOSE 23000

CMD ["npx", "vite", "preview", "--config", "./vite.config.ts", "--host", "0.0.0.0", "--port", "23000"] 