FROM --platform=linux/amd64 node:20-alpine AS builder

WORKDIR /app

COPY lugia-frontend/package.json ./
COPY lugia-frontend/package-lock.json ./

# Use E2E specific configurations by copying them to default config file names
COPY lugia-frontend/test/svelte.e2e.config.js ./svelte.config.js
COPY lugia-frontend/test/vite.e2e.config.ts ./vite.config.ts
COPY lugia-frontend/tsconfig.json ./

# Copy the E2E-specific .env file to .env for the build
COPY lugia-frontend/.env.e2e ./.env

# Build component library first
COPY zoroark /zoroark
WORKDIR /zoroark
RUN npm install --no-frozen-lockfile
RUN npm run build

# Copy the rest of the lugia-frontend application source code
WORKDIR /app
COPY lugia-frontend/. .

# Create symlink to built zoroark library
RUN ln -sf /zoroark ../zoroark

RUN rm -rf node_modules package-lock.json || true
RUN npm install --no-frozen-lockfile

RUN npm run build

EXPOSE 23000

CMD ["npx", "vite", "preview", "--config", "./test/vite.e2e.config.ts", "--host", "0.0.0.0", "--port", "23000"] 