DROP TABLE IF EXISTS email_change_tokens;
DROP TABLE IF EXISTS goose_db_version;
DROP TABLE IF EXISTS invitation_tokens;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE user_roles;
DROP TABLE role_permissions;
DROP TABLE permissions;
DROP TABLE roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;