// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error)
	CreateTenant(ctx context.Context, name string) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	GetRefreshTokenByJTI(ctx context.Context, jti pgtype.UUID) (*RefreshToken, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
