#!/usr/bin/env bash
set -euo pipefail

# Test Scout Runner
# Orchestrates: test-scout (write tests) -> review (quality gate) -> PR creation
# Usage: ./scripts/test-scout-runner.sh [target]
# Example: ./scripts/test-scout-runner.sh jirachi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

TARGET="${1:-}"
BRANCH_NAME="test-scout/$(date +%Y%m%d-%H%M%S)"

# Ensure clean working directory
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: working directory is not clean. Commit or stash changes first."
  exit 1
fi

# Create and switch to a new branch
MAIN_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
git checkout "$MAIN_BRANCH"
git pull origin "$MAIN_BRANCH"
git checkout -b "$BRANCH_NAME"

echo "=== Phase 1: Test Scout ==="
echo "Branch: $BRANCH_NAME"
echo "Target: ${TARGET:-full codebase}"

if [ -n "$TARGET" ]; then
  claude --remote "/test-scout $TARGET" --allowedTools "Bash,Read,Write,Edit,Glob,Grep,Agent"
else
  claude --remote "/test-scout" --allowedTools "Bash,Read,Write,Edit,Glob,Grep,Agent"
fi

# Check if the scout actually made changes
if [ -z "$(git status --porcelain)" ]; then
  echo "Test scout made no changes. Nothing to review."
  git checkout "$MAIN_BRANCH"
  git branch -D "$BRANCH_NAME"
  exit 0
fi

echo ""
echo "=== Phase 2: Review ==="

REVIEW_OUTPUT=$(claude -p "/review" --allowedTools "Bash,Read,Glob,Grep,Agent" 2>&1)
echo "$REVIEW_OUTPUT"

# Check if review passed (look for "ready to commit" or "Clean" in output)
if echo "$REVIEW_OUTPUT" | grep -qi "ready to commit\|self-review passed\|clean"; then
  echo ""
  echo "=== Phase 3: Create PR ==="
  git push -u origin "$BRANCH_NAME"
  gh pr create \
    --title "test: add tests from test-scout ($(date +%Y-%m-%d))" \
    --body "$(cat <<'EOF'
## What

Automated test additions from the test-scout agent.

## Why

Improve test coverage by finding and filling gaps in the test suite.

## How

1. Test scout agent identified undertested code and wrote tests
2. Review agent verified test quality

## Testing

- [x] Tests pass (`make verify` or module-specific test command)
- [x] Automated review passed

## Review notes

This PR was generated by the test-scout runner. Please review the tests for quality and relevance.
EOF
)"
  echo ""
  echo "PR created successfully."
else
  echo ""
  echo "=== Review found issues ==="
  echo "The review agent flagged problems. Branch '$BRANCH_NAME' has the changes."
  echo "Switch to it manually to inspect: git checkout $BRANCH_NAME"
  exit 1
fi
