// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const InsertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (tenant_id, actor_id, resource_type, action, outcome, resource_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ResourceType string      `json:"resource_type"`
	Action       string      `json:"action"`
	Outcome      string      `json:"outcome"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg *InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, InsertAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.ResourceType,
		arg.Action,
		arg.Outcome,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
