// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    jti,
    device_info,
    ip_address,
    expires_at
) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, jti, device_info, ip_address, expires_at, created_at, used_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Jti        pgtype.UUID        `json:"jti"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, CreateRefreshToken,
		arg.UserID,
		arg.Jti,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const GetRefreshTokenByUserID = `-- name: GetRefreshTokenByUserID :one
SELECT id, user_id, jti, device_info, ip_address, expires_at, created_at, used_at, revoked_at FROM refresh_tokens 
WHERE user_id = $1 
AND revoked_at IS NULL 
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, GetRefreshTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const GetTenantByID = `-- name: GetTenantByID :one
SELECT id, name, enterprise_features, stripe_customer_id, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error) {
	row := q.db.QueryRow(ctx, GetTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnterpriseFeatures,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, is_internal_admin, created_at, updated_at, status FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsInternalAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, is_internal_admin, created_at, updated_at, status FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsInternalAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return &i, err
}

const RevokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP 
WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeRefreshToken, jti)
	return err
}

const UpdateRefreshTokenUsed = `-- name: UpdateRefreshTokenUsed :exec
UPDATE refresh_tokens 
SET used_at = CURRENT_TIMESTAMP 
WHERE jti = $1
`

func (q *Queries) UpdateRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) error {
	_, err := q.db.Exec(ctx, UpdateRefreshTokenUsed, jti)
	return err
}
