// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"
)

type Querier interface {
	GetTenants(ctx context.Context) ([]*Tenant, error)
}

var _ Querier = (*Queries)(nil)
