// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetTenantByID = `-- name: GetTenantByID :one
SELECT id, name, enterprise_features, stripe_customer_id, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error) {
	row := q.db.QueryRow(ctx, GetTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnterpriseFeatures,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetTenants = `-- name: GetTenants :many
SELECT id, name, enterprise_features, stripe_customer_id, created_at, updated_at FROM tenants ORDER BY created_at ASC
`

func (q *Queries) GetTenants(ctx context.Context) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, GetTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnterpriseFeatures,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTenant = `-- name: UpdateTenant :exec
UPDATE tenants
SET name = $1, enterprise_features = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateTenantParams struct {
	Name               string      `json:"name"`
	EnterpriseFeatures []byte      `json:"enterprise_features"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg *UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, UpdateTenant, arg.Name, arg.EnterpriseFeatures, arg.ID)
	return err
}
