// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package queries

import (
	"context"
)

const GetTenants = `-- name: GetTenants :many
select id, name, enterprise_features, stripe_customer_id, created_at, updated_at from tenants
`

func (q *Queries) GetTenants(ctx context.Context) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, GetTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnterpriseFeatures,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
