#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"

PROMPT="${1:-}"
if [ -z "${PROMPT}" ]; then
    echo "Usage: ./run-task.sh \"<prompt>\" [branch-suffix]"
    echo ""
    echo "Examples:"
    echo "  ./run-task.sh \"Add input validation to the login endpoint\""
    echo "  ./run-task.sh \"Refactor jirachi/auth to use context-based errors\" auth-refactor"
    exit 1
fi

BRANCH_SUFFIX="${2:-}"
SESSION_ID="$(date +%s)-$(head -c 4 /dev/urandom | xxd -p)"
if [ -n "${BRANCH_SUFFIX}" ]; then
    BRANCH="agent/${BRANCH_SUFFIX}"
else
    BRANCH="agent/${SESSION_ID}"
fi
WORKTREE="/tmp/agent-${SESSION_ID}"
COMPOSE_PROJECT="agent-${SESSION_ID}"
REPO_TAR="/tmp/agent-${SESSION_ID}.tar"
PATCHES_DIR="/tmp/agent-${SESSION_ID}-patches"

echo "=== Agent Task Runner ==="
echo "Session:  ${SESSION_ID}"
echo "Branch:   ${BRANCH}"
echo "Worktree: ${WORKTREE}"
echo "Prompt:   ${PROMPT}"
echo ""

# Load token from .env.sensitive if not already set
if [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -f "${SCRIPT_DIR}/.env.sensitive" ]; then
    set -a
    source "${SCRIPT_DIR}/.env.sensitive"
    set +a
fi

if [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    echo "ERROR: CLAUDE_CODE_OAUTH_TOKEN is not set."
    echo "Either create agent/.env.sensitive with CLAUDE_CODE_OAUTH_TOKEN=<token>"
    echo "or: export CLAUDE_CODE_OAUTH_TOKEN=<token>"
    echo ""
    echo "Generate a token with: claude setup-token"
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo "ERROR: docker is not installed"
    exit 1
fi

if ! command -v gh &>/dev/null; then
    echo "ERROR: gh (GitHub CLI) is not installed"
    exit 1
fi

# Cleanup on exit (success or failure)
cleanup() {
    echo ""
    echo "=== Cleanup ==="
    REPO_TAR="${REPO_TAR}" docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" down --volumes 2>/dev/null || true
    git -C "${REPO_ROOT}" worktree remove "${WORKTREE}" --force 2>/dev/null || true
    rm -f "${REPO_TAR}"
    rm -rf "${PATCHES_DIR}"
    echo "Done."
}
trap cleanup EXIT

# 1. Create worktree from main
echo "Creating worktree from main..."
git -C "${REPO_ROOT}" worktree add "${WORKTREE}" --detach main -q

# 2. Create clean repo tarball (no .git metadata)
echo "Creating repo archive..."
git -C "${WORKTREE}" archive --format=tar HEAD -o "${REPO_TAR}"

# 3. Start environment
export REPO_TAR
export CLAUDE_CODE_OAUTH_TOKEN
export AGENT_PROMPT="${PROMPT}"
export AGENT_MODEL="${AGENT_MODEL:-opus}"
export AGENT_ENTRYPOINT="entrypoint-task.sh"
export AGENT_MAX_REVIEW_ITERATIONS="${AGENT_MAX_REVIEW_ITERATIONS:-3}"

echo ""
echo "=== Starting Agent ==="
echo ""

set +e
docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" up \
    --exit-code-from agent \
    --build 2>&1
AGENT_EXIT=$?
set -e

if [ $AGENT_EXIT -ne 0 ]; then
    echo ""
    echo "Agent exited with code ${AGENT_EXIT}."
    exit $AGENT_EXIT
fi

# 4. Extract patches from container
AGENT_CONTAINER=$(docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" ps -aq agent)

if [ -z "${AGENT_CONTAINER}" ]; then
    echo "ERROR: Could not find agent container"
    exit 1
fi

mkdir -p "${PATCHES_DIR}"
docker cp "${AGENT_CONTAINER}:/workspace/patches/." "${PATCHES_DIR}/" 2>/dev/null || true

PATCH_COUNT=$(find "${PATCHES_DIR}" -name "*.patch" 2>/dev/null | wc -l | tr -d ' ')
if [ "${PATCH_COUNT}" -eq 0 ]; then
    echo ""
    echo "No patches generated — agent made no changes."
    exit 0
fi

echo ""
echo "=== ${PATCH_COUNT} patch(es) found ==="

# 5. Apply patches to worktree
cd "${WORKTREE}"
git am "${PATCHES_DIR}"/*.patch -q

# 6. Push and create PR
echo "Pushing to ${BRANCH}..."
git push origin "HEAD:refs/heads/${BRANCH}" -q

# Truncate prompt for title (max 60 chars)
PR_TITLE_PROMPT="${PROMPT}"
if [ ${#PR_TITLE_PROMPT} -gt 60 ]; then
    PR_TITLE_PROMPT="${PR_TITLE_PROMPT:0:57}..."
fi
PR_TITLE="agent: ${PR_TITLE_PROMPT}"

PR_BODY=$(cat <<EOF
## What

Automated changes by agent task runner.

## Prompt

> ${PROMPT}

## Details

- Session: \`${SESSION_ID}\`
- Model: \`${AGENT_MODEL}\`
- Review iterations: up to ${AGENT_MAX_REVIEW_ITERATIONS}

## Scope

- [x] Changes are scoped to the task — no unrelated modifications
- [ ] Generated code (SQLC, OpenAPI) was regenerated, not hand-edited

## Testing

- [ ] \`make verify\` passes from root

## Review notes

This PR was generated by an autonomous agent. Review for correctness and quality before merging.
EOF
)

PR_URL=$(gh pr create \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    --base main \
    --head "${BRANCH}" \
    --repo "$(git remote get-url origin)")

echo ""
echo "=== PR Created ==="
echo "${PR_URL}"
