#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"

TARGET="${1:-}"
SESSION_ID="$(date +%s)-$(head -c 4 /dev/urandom | xxd -p)"
BRANCH="test-scout/${SESSION_ID}"
WORKTREE="/tmp/scout-${SESSION_ID}"
COMPOSE_PROJECT="scout-${SESSION_ID}"
REPO_TAR="/tmp/scout-${SESSION_ID}.tar"
PATCHES_DIR="/tmp/scout-${SESSION_ID}-patches"

echo "=== Test Scout Runner ==="
echo "Session:  ${SESSION_ID}"
echo "Target:   ${TARGET:-<roaming>}"
echo "Branch:   ${BRANCH}"
echo "Worktree: ${WORKTREE}"
echo ""

# Load token from .env.sensitive if not already set
if [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -f "${SCRIPT_DIR}/.env.sensitive" ]; then
    set -a
    source "${SCRIPT_DIR}/.env.sensitive"
    set +a
fi

if [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    echo "ERROR: CLAUDE_CODE_OAUTH_TOKEN is not set."
    echo "Either create agent/.env.sensitive with CLAUDE_CODE_OAUTH_TOKEN=<token>"
    echo "or: export CLAUDE_CODE_OAUTH_TOKEN=<token>"
    echo ""
    echo "Generate a token with: claude setup-token"
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo "ERROR: docker is not installed"
    exit 1
fi

if ! command -v gh &>/dev/null; then
    echo "ERROR: gh (GitHub CLI) is not installed"
    exit 1
fi

# Cleanup on exit (success or failure)
cleanup() {
    echo ""
    echo "=== Cleanup ==="
    REPO_TAR="${REPO_TAR}" docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" down --volumes 2>/dev/null || true
    git -C "${REPO_ROOT}" worktree remove "${WORKTREE}" --force 2>/dev/null || true
    rm -f "${REPO_TAR}"
    rm -rf "${PATCHES_DIR}"
    echo "Done."
}
trap cleanup EXIT

# 1. Create worktree from main
echo "Creating worktree from main..."
git -C "${REPO_ROOT}" worktree add "${WORKTREE}" --detach main -q

# 2. Create clean repo tarball (no .git metadata)
echo "Creating repo archive..."
git -C "${WORKTREE}" archive --format=tar HEAD -o "${REPO_TAR}"

# 3. Start environment
export REPO_TAR
export CLAUDE_CODE_OAUTH_TOKEN
export AGENT_TARGET="${TARGET}"
export AGENT_MODEL="${AGENT_MODEL:-opus}"

echo ""
echo "=== Starting Agent ==="
echo ""

set +e
docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" up \
    --exit-code-from agent \
    --build 2>&1
AGENT_EXIT=$?
set -e

if [ $AGENT_EXIT -ne 0 ]; then
    echo ""
    echo "Agent exited with code ${AGENT_EXIT}."
    exit $AGENT_EXIT
fi

# 4. Extract patches from container
AGENT_CONTAINER=$(docker compose -p "${COMPOSE_PROJECT}" -f "${COMPOSE_FILE}" ps -aq agent)

if [ -z "${AGENT_CONTAINER}" ]; then
    echo "ERROR: Could not find agent container"
    exit 1
fi

mkdir -p "${PATCHES_DIR}"
docker cp "${AGENT_CONTAINER}:/workspace/patches/." "${PATCHES_DIR}/" 2>/dev/null || true

PATCH_COUNT=$(find "${PATCHES_DIR}" -name "*.patch" 2>/dev/null | wc -l | tr -d ' ')
if [ "${PATCH_COUNT}" -eq 0 ]; then
    echo ""
    echo "No patches generated — agent made no changes."
    exit 0
fi

echo ""
echo "=== ${PATCH_COUNT} patch(es) found ==="

# 5. Apply patches to worktree
cd "${WORKTREE}"
git am "${PATCHES_DIR}"/*.patch -q

# 6. Push and create PR
echo "Pushing to ${BRANCH}..."
git push origin "HEAD:refs/heads/${BRANCH}" -q

PR_TITLE="test-scout: ${TARGET:-automated test additions}"
PR_BODY=$(cat <<EOF
## What

Automated test additions by test-scout agent.

## Why

Improve test coverage for undertested code.

## How

Autonomous agent roamed the codebase, identified gaps, and wrote tests.

- Session: \`${SESSION_ID}\`
- Target: \`${TARGET:-<roaming>}\`
- Model: \`${AGENT_MODEL}\`

## Scope

- [x] Changes are scoped to the task — no unrelated modifications
- [ ] Generated code (SQLC, OpenAPI) was regenerated, not hand-edited

## Testing

- [ ] \`make verify\` passes from root

## Review notes

This PR was generated by an autonomous agent. Review the tests for correctness and quality before merging.
EOF
)

PR_URL=$(gh pr create \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    --base main \
    --head "${BRANCH}" \
    --repo "$(git remote get-url origin)")

echo ""
echo "=== PR Created ==="
echo "${PR_URL}"
