// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Plan      string
	Status    pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
	Name         pgtype.Text
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Status       pgtype.Text
}
