// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg *CreateRefreshTokenParams) (*RefreshToken, error)
	CreateTenant(ctx context.Context, arg *CreateTenantParams) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (*Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserRefreshToken(ctx context.Context, userID pgtype.UUID) (*RefreshToken, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	UpdateRefreshTokenLastUsed(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
