// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetUsersByTenantID = `-- name: GetUsersByTenantID :many
SELECT id, email, name, role, status, created_at, updated_at
FROM users
WHERE tenant_id = $1
ORDER BY created_at ASC
`

type GetUsersByTenantIDRow struct {
	ID        pgtype.UUID
	Email     string
	Name      pgtype.Text
	Role      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUsersByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]*GetUsersByTenantIDRow, error) {
	rows, err := q.db.Query(ctx, GetUsersByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersByTenantIDRow{}
	for rows.Next() {
		var i GetUsersByTenantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InviteUserToTenant = `-- name: InviteUserToTenant :exec
INSERT INTO users (tenant_id, email, password_hash, name, role, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InviteUserToTenantParams struct {
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
	Name         pgtype.Text
	Role         string
	Status       string
}

func (q *Queries) InviteUserToTenant(ctx context.Context, arg *InviteUserToTenantParams) error {
	_, err := q.db.Exec(ctx, InviteUserToTenant,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.Status,
	)
	return err
}
